### ISSUE TITLE
Feature 1: User can create a post

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a post.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking 'new post' in the nav menu will bring up the form to create a new post. There will be inputs for a photo, caption, location, and cooked/bought. Pressing 'share' will submit the form and user will be taken to the home page to view their new post.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-13 at 1 29 24 PM](https://user-images.githubusercontent.com/87846307/163265087-d5d12b9b-ec62-4bdc-9e06-14353d23fb5a.png)

<img width="443" alt="Screen Shot 2022-04-11 at 4 41 32 PM" src="https://user-images.githubusercontent.com/87846307/162850511-da8aaae9-2894-4580-9d8d-67efa2a73570.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have 5 tables: photos, users, comments, followers, and likes.
- [x] Update `data.sql` to have two test users.

### ☁️ Server

- [x] Update `server/index.js` to have a 'post' request after user submits form.
- [x] Query the database to insert provided inputs
- [x] Add uploadsMiddleware file and require it for index.js
- [x] Test 'post' request with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create Form component and add form inputs
- [x] Add onChange, click, and submit events to form inputs
- [x] Create formData variable and append all inputs
- [x] Make all inputs required, except for location
- [x] Add fetch request for when post form is submitted
- [x] Style and format Form component
- [x] Add image preview for file upload
- [x] Add post form component to main app component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
