### ISSUE TITLE
Feature 6: User can unlike posts

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can unlike a post.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user chooses to unlike a post, they can click the filled heart icon and it'll turn into an unfilled heart and the likes counter will decrement by 1.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="567" alt="Screen Shot 2022-04-19 at 1 22 34 PM" src="https://user-images.githubusercontent.com/87846307/164089392-7b403691-488d-4635-9652-fa3148ff43e8.png">
<img width="780" alt="Screen Shot 2022-04-19 at 1 22 55 PM" src="https://user-images.githubusercontent.com/87846307/164089401-6ae19b13-40ce-4337-a87b-a9938828e7f0.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have 'DELETE' route for 'likes' table based on postId
- [x] Test 'DELETE' route with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update Post component to conditionally fetch 'DELETE' from likes table when filled heart clicked

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
