### ISSUE TITLE
Feature 7: User can comment on posts 

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can comment on posts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks 'view comments' they'll be given a text box to type a comment

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="749" alt="Screen Shot 2022-04-20 at 11 37 09 AM" src="https://user-images.githubusercontent.com/87846307/164299942-754b2ef4-de05-4eda-b588-a2a0577a9903.png">
<img width="866" alt="Screen Shot 2022-04-20 at 11 37 45 AM" src="https://user-images.githubusercontent.com/87846307/164299963-89c3e4be-7002-45e0-94cf-2b9b3cf4bf2b.png">
<img width="868" alt="Screen Shot 2022-04-20 at 11 37 34 AM" src="https://user-images.githubusercontent.com/87846307/164299975-ac77c890-52f7-4fa8-8ea9-07e965f05fd6.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have 'comments' table with 'message' field
- [x] Update `data.sql` to have dummy data for 'comments' table.

### ☁️ Server

- [x] Update `server/index.js` to have new 'POST' route for comments based on postId
- [x] Test 'POST' route with HTTPie
- [x] Update `server/index.js` to have new 'GET' route for comments based on postId
- [x] Join 'users' table for username and profilePhoto in comments 'GET' route
- [x] Test 'GET' route with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update Post component to fetch 'GET' comments when componentDidMount() and store it in 'comments' state
- [x] Create new Comment component
- [x] Map through 'comments' state and render in Comment component
- [x] Add 'view comments' button and onClick handler to conditionally render comments
- [x] Update Post component to fetch 'POST' when comment is submitted
- [x] Update Post component submit handler to fetch 'GET' comments
- [x] Update timestamp using date-fns library
- [x] Style comments section to match Figma design

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
