### ISSUE TITLE
Feature 8: User can view all posts

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all posts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When on the home screen, the page will populate with all posts in the database.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="582" alt="Screen Shot 2022-04-20 at 12 45 17 PM" src="https://user-images.githubusercontent.com/87846307/164310695-483aa988-ecde-4d6f-ac88-0e80fef78e34.png">
<img width="227" alt="Screen Shot 2022-04-20 at 12 45 30 PM" src="https://user-images.githubusercontent.com/87846307/164310702-a8579ee6-9703-4090-b015-9d83d40b8b60.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have 'GET' route to retrieve all posts
- [x] Test 'GET' route with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update Home component to fetch 'GET' request when componentDidMount()
- [x] Store 'GET' request data in state
- [x] Map through all posts and pass each post as a prop to the Post component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
