### ISSUE TITLE
Feature 9: User can sign up for an account

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up for an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When app loads up, users are given the option to sign up for an account. They'll need to input a username and a password.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Require argon2 to hash passwords in server/index.js
- [x] Update `server/index.js` to have a 'POST' route for account sign-ups
- [x] Test 'POST' route with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Rename current Form component to PostForm
- [x] Create an AuthForm component in 'component' directory and a Auth component in 'pages' directory
- [x] Add hash route for 'sign-up' in App component
- [x] Style both Auth and AuthForm component
- [x] Create onChange handlers in AuthForm to store user inputs in state
- [x] Create submit handler that initiates a 'POST' request for user sign up

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
