### ISSUE TITLE
Feature 10: User can sign into their account

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign into their account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can enter their username and password 

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have 'POST' route for sign-in
- [x] Test 'POST' route with HTTPie
- [x] Update 'error-middleware.js' to handle invalid JSON Web Tokens
- [x] Create 'authorization-middleware.js' and require 'jsonwebtoken'
- [x] Require authorization-middlware in index.js and place every route that doesn't require a 'user' prop above it
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create decode-token.js file in 'lib' directory for payload
- [x] Update App component to have handleSignIn function to store user and jwt
- [x] Add conditional hash route path for 'sign-in' in App component
- [x] Add handleSignIn and user to contextValue in App component
- [x] Access user and handleSignIn with this.context in Auth component
- [x] Pass handleSignIn to AuthForm via props
- [x] Create Redirect component to handle pages based on user
- [x] Import Redirect component into Auth.jsx and Home.jsx
- [x] Add fetch 'POST' for user sign-in in AuthForm component
- [x] Include 'X-Access-Token' header in all necessary fetch requests and set userId based on req.user in server routes.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
