### ISSUE TITLE
Feature 11: User can sign out of their account

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out of their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to sign out of their account by clicking 'my profile' in the navbar and then 'sign out'.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update App component to have handleSignOut method
- [x] Remove user token from local storage in handleSignOut and set user to null
- [x] Pass handleSignOut into contextValue of App component
- [x] Access handleSignOut with this.context in Navbar component
- [x] Create DropwdownMenu component and import into Navbar
- [x] Redirect user to AuthForm sign-in route upon sign-out

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
