### ISSUE TITLE
Feature 12: User can view other profiles

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view other profiles

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking usernames or profile pictures at the top of a post will take user to corresponding profile page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="479" alt="Screen Shot 2022-04-22 at 11 44 19 AM" src="https://user-images.githubusercontent.com/87846307/164775541-319bf10d-7893-4868-919f-10e78942cd08.png">
<img width="267" alt="Screen Shot 2022-04-22 at 11 44 58 AM" src="https://user-images.githubusercontent.com/87846307/164775549-df09e99d-db33-45ea-b0d8-e1a1693e05ca.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` 'GET' route for all posts to include userId in its query
- [x] Test 'GET' route with HTTPie
- [x]  Update `server/index.js` to have 'GET' route for retrieving user data based on userId
- [x] Test user 'GET' route with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Refactor Profile and PostHistory components to fetch 'GET' in PostHistory
- [x] Retrieve userId variable in Post component
- [x] Update hash routing in App component
- [x] Fetch 'GET' user data in componentDidMount() to populate Profile component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
