### ISSUE TITLE
Feature 13: User can follow a profile

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can follow a profile

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user is on another profile they'll have the option to press the 'follow' button. It'll increment that profile's follower counter and also the logged in user's following counter.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="479" alt="Screen Shot 2022-04-22 at 11 44 19 AM" src="https://user-images.githubusercontent.com/87846307/164815139-2b6d7dfb-ea16-456b-a443-df7073f3fc5c.png">
<img width="267" alt="Screen Shot 2022-04-22 at 11 44 58 AM" src="https://user-images.githubusercontent.com/87846307/164815140-f5bdbf4f-5677-4b39-addd-d196b552d1e2.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to remove followerCount, followingCount, and postCount from users table
- [x] Update `data.sql` to remove followerCount, followingCount, and postCount from users

### ☁️ Server

- [x] Update `server/index.js` to have 'POST' route for inserting into followers table based on userId
- [x] Test 'POST' route with HTTPie
- [x] Update 'GET' route for a single user to 'Count' as postCount, followerCount and followingCount
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update Profile component to render a follow button
- [x] Update Profile component to have handler and state for a follow button
- [x] Fetch 'Post' on follow clicks

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
