### ISSUE TITLE
Feature 2: User can view their posts

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their posts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-14 at 3 55 33 PM](https://user-images.githubusercontent.com/87846307/163490741-067c8c94-ba19-485e-a9aa-4b6a345afc92.png)
![Screen Shot 2022-04-14 at 3 55 41 PM](https://user-images.githubusercontent.com/87846307/163490745-d59f03fd-e64d-44b3-b918-7505e97f6226.png)
![Screen Shot 2022-04-14 at 3 56 32 PM](https://user-images.githubusercontent.com/87846307/163490748-ab7f38cf-5ef9-4e2c-9400-8f61d3a0d2e2.png)

### 🐘 Database

- [x] Update `data.sql` to have one more test photo

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a 'get' request for when user clicks their profile
- [x] Query the database to select all photos with matching userId
- [x] Test 'get' request with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a Profile component
- [x] Create a Post component to render each post fetched from database
- [x] Add fetch request on componentDidMount() to Post component
- [x] Map() through the photo list
- [x] Ensure posts are shown in order (most recent first)
- [x] Format timestamp using data-fns
- [x] Create Navbar component to have logo and menu items
- [x] Style Navbar component
- [x] Create a lib folder and add parse-route.js
- [x] Add this.state.route in app.jsx for hash routing
- [x] Add an event listener in compondentDidMount() in app.jsx for hashchange events
- [x] Create renderPage() in app.jsx to render based on hash route
- [x] Create app-context.js in lib directory and make App.jsx a provider
- [x] Add appropriate href attribute to all components
- [x] Style and format Profile component
- [x] Add conditional screen for if user has no posts

### 🧑‍⚕️ Clean Up

- [x] Make sure navbar closes on hashchange
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
