### ISSUE TITLE
Feature 3: User can update their posts

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can update their posts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user is on their profile and click pen icon, they can edit/update their existing post. They can change the image, caption, location, and whether or not it was home-cooked or bought.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="537" alt="Screen Shot 2022-04-14 at 4 45 30 PM" src="https://user-images.githubusercontent.com/87846307/163494197-916d28bb-07b2-426f-a3f4-fe5bbe8c4a50.png">
<img width="741" alt="Screen Shot 2022-04-14 at 4 46 38 PM" src="https://user-images.githubusercontent.com/87846307/163494292-1cc98639-6fb3-4ce0-8633-fe54c87f655c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have 'editedAt' in 'posts table, allow nulls

### ☁️ Server

- [x] Update `server/index.js` to have 'GET' request based on postId
- [x] Test 'GET' request with HTTPie
- [x] Update `server/index.js` to have 'PUT' request based on postId
- [x] Test 'PUT' request with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update PostHistory component to have edit icon
- [x] Add hashchange for edit icon (href={'#edit-post?postId=${postId}'}
- [x] Set up hash routing to render page for Form component and pass prop - postId route param
- [x] Add conditional to fetch 'GET' in componentDidMount() of Form component and set form's state based on fetched data
- [x] Ensure radio button for 'isBought' is checked on Form edit render
- [x] Add condition to send 'POST' if this.props.postId is falsy, else send "PUT'
- [x] Add condition to change text to 'Edit Post' in Form component
- [x] Add condition to change timestamp based on 'editedAt' in Form component
- [x] Add condition to change share button to 'save' in Form component
- [x] Ensure edited post is updated in the database
- [x] Ensure posts are displayed in the same order based on 'postId' with most recent at top
- [x] Hashchange to home page when form is submitted for new posts and to profile for edits

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
