### ISSUE TITLE
Feature 4: User can delete their posts

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete their posts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks edit icon the form will now have a delete icon which will bring up a modal to confirm deletion of post.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="569" alt="Screen Shot 2022-04-16 at 5 36 07 PM" src="https://user-images.githubusercontent.com/87846307/163695457-4379ab50-e249-45e4-83e7-b0c899a4450b.png">
<img width="793" alt="Screen Shot 2022-04-16 at 5 36 54 PM" src="https://user-images.githubusercontent.com/87846307/163695466-a081b69a-370a-4ee7-b1a5-7591030e58e4.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have 'DELETE' request based on postId
- [x] Test 'DELETE' request with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update Form component to have red delete icon
- [x] Add condition to only render delete icon on Form edits
- [x] Add onClick event to show modal when delete icon is clicked
- [x] Add fetch 'DELETE' in Form component
- [x] Hashchange to profile when post delete is confirmed

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
