### ISSUE TITLE
Feature 5: User can like a post

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can like a post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on heart icon it will be filled red and then the likes counter will increment by 1

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="533" alt="Screen Shot 2022-04-16 at 6 21 49 PM" src="https://user-images.githubusercontent.com/87846307/163696275-e1e67bce-ec15-4aa9-870c-ff4abebf7abe.png">
<img width="753" alt="Screen Shot 2022-04-16 at 6 21 33 PM" src="https://user-images.githubusercontent.com/87846307/163696278-33698fd5-600d-442c-bd01-b32ff76c0073.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to have dummy data for likes

### ☁️ Server

- [x] Update `server/index.js` to have 'POST' request based on postId for likes
- [x] Test 'POST' request with HTTPie
- [x] Update `server/index.js` current 'GET' requests to count # of likes based on postId
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Separate Post function into it's own module in the components directory
- [x] import Post component in PostHistory component
- [x] Add heart-icon.jsx file for likes on a post
- [x] Update Post component to render heart icon and likes counter
- [x] Add fetch 'POST' in PostHistory component when heart icon is clicked

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
